// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdvProfile = "t_amz_adv_profile"

// AdvProfile mapped from table <t_amz_adv_profile>
type AdvProfile struct {
	ID            int64     `gorm:"column:id;primaryKey" json:"id"`
	CountryCode   string    `gorm:"column:countryCode" json:"countryCode"`
	CurrencyCode  string    `gorm:"column:currencyCode" json:"currencyCode"`
	MarketplaceID string    `gorm:"column:marketplaceId" json:"marketplaceId"`
	SellerID      string    `gorm:"column:sellerId" json:"sellerId"`
	AdvauthID     string    `gorm:"column:advauthId" json:"advauthId"`
	Timezone      string    `gorm:"column:timezone" json:"timezone"`
	Type          string    `gorm:"column:type" json:"type"`
	DailyBudget   float64   `gorm:"column:dailyBudget" json:"dailyBudget"`
	Errorday      time.Time `gorm:"column:errorday" json:"errorday"`
	Opttime       time.Time `gorm:"column:opttime" json:"opttime"`
	Errorlog      string    `gorm:"column:errorlog" json:"errorlog"`
}

// TableName AdvProfile's table name
func (*AdvProfile) TableName() string {
	return TableNameAdvProfile
}
