// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAmazonAuth = "t_amazon_auth"

// AmazonAuth mapped from table <t_amazon_auth>
type AmazonAuth struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	ShopID           string    `gorm:"column:shop_id;comment:用户ID" json:"shop_id"`            // 用户ID
	Sellerid         string    `gorm:"column:sellerid;not null;comment:卖家ID" json:"sellerid"` // 卖家ID
	Groupid          string    `gorm:"column:groupid" json:"groupid"`
	Region           string    `gorm:"column:region" json:"region"`
	MWSAuthToken     string    `gorm:"column:MWSAuthToken;comment:卖家授权码" json:"MWSAuthToken"` // 卖家授权码
	Disable          []uint8   `gorm:"column:disable;default:b'0" json:"disable"`
	Name             string    `gorm:"column:name" json:"name"`
	PictureID        string    `gorm:"column:pictureId" json:"pictureId"`
	Status           string    `gorm:"column:status" json:"status"`
	Statusupdate     time.Time `gorm:"column:statusupdate" json:"statusupdate"`
	Productdate      time.Time `gorm:"column:productdate" json:"productdate"`
	Refreshinvtime   time.Time `gorm:"column:refreshinvtime" json:"refreshinvtime"`
	RefreshToken     string    `gorm:"column:refresh_token" json:"refresh_token"`
	RefreshTokenTime time.Time `gorm:"column:refresh_token_time" json:"refresh_token_time"`
	AwsRegion        string    `gorm:"column:aws_region" json:"aws_region"`
	Createtime       time.Time `gorm:"column:createtime" json:"createtime"`
	Opttime          time.Time `gorm:"column:opttime" json:"opttime"`
	Oldid            string    `gorm:"column:oldid" json:"oldid"`
	ConfigID         int32     `gorm:"column:config_id" json:"config_id"`
}

// TableName AmazonAuth's table name
func (*AmazonAuth) TableName() string {
	return TableNameAmazonAuth
}
