// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdvAutoLog = "t_amz_adv_auto_log"

// AdvAutoLog mapped from table <t_amz_adv_auto_log>
type AdvAutoLog struct {
	ID                  int64     `gorm:"column:id;primaryKey" json:"id"`
	ProfileID           int64     `gorm:"column:profile_id;not null;comment:站点ID" json:"profile_id"`                             // 站点ID
	PortfolioID         int64     `gorm:"column:portfolio_id;comment:广告组合id" json:"portfolio_id"`                                // 广告组合id
	CampaignID          int64     `gorm:"column:campaign_id;comment:活动ID" json:"campaign_id"`                                    // 活动ID
	CampaignName        string    `gorm:"column:campaign_name;comment:广告活动" json:"campaign_name"`                                // 广告活动
	Sence               int32     `gorm:"column:sence;comment:场景 0-规则编辑日志, 1-自动化日志" json:"sence"`                                // 场景 0-规则编辑日志, 1-自动化日志
	RuleID              int64     `gorm:"column:rule_id;comment:规则ID" json:"rule_id"`                                            // 规则ID
	RuleType            int32     `gorm:"column:rule_type;comment:规则类型 1分时预算,2分时调价，3自动竞价，4自动广告位" json:"rule_type"`               // 规则类型 1分时预算,2分时调价，3自动竞价，4自动广告位
	RuleTypeName        string    `gorm:"column:rule_type_name;comment:规则名称" json:"rule_type_name"`                              // 规则名称
	ExecuteFrequencyDay int32     `gorm:"column:execute_frequency_day;comment:执行频率 7 ,14 ,30" json:"execute_frequency_day"`      // 执行频率 7 ,14 ,30
	Beanclasz           string    `gorm:"column:beanclasz;comment:执行类" json:"beanclasz"`                                         // 执行类
	LastID              int64     `gorm:"column:last_id;comment:上一次执行的id" json:"last_id"`                                        // 上一次执行的id
	OptBefore           string    `gorm:"column:opt_before;comment:操作前" json:"opt_before"`                                       // 操作前
	OptAfter            string    `gorm:"column:opt_after;comment:操作后" json:"opt_after"`                                         // 操作后
	RangeStartTime      time.Time `gorm:"column:range_start_time;comment:执行范围-开始时间" json:"range_start_time"`                     // 执行范围-开始时间
	RangeEndTime        time.Time `gorm:"column:range_end_time;comment:执行范围-结束时间" json:"range_end_time"`                         // 执行范围-结束时间
	Result              string    `gorm:"column:result;comment:操作结果" json:"result"`                                              // 操作结果
	Remark              string    `gorm:"column:remark;comment:操作说明" json:"remark"`                                              // 操作说明
	Opttime             time.Time `gorm:"column:opttime;not null;comment:操作时间" json:"opttime"`                                   // 操作时间
	Operator            string    `gorm:"column:operator;comment:操作人姓名" json:"operator"`                                         // 操作人姓名
	CreateTime          time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime          time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName AdvAutoLog's table name
func (*AdvAutoLog) TableName() string {
	return TableNameAdvAutoLog
}
