// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAmsSalesEvent = "t_ams_sales_event"

// AmsSalesEvent mapped from table <t_ams_sales_event>
type AmsSalesEvent struct {
	ID               int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AccountID        string    `gorm:"column:account_id;not null;comment:账号id" json:"account_id"`                             // 账号id
	SellerID         string    `gorm:"column:seller_id;comment:店铺id" json:"seller_id"`                                        // 店铺id
	MarketplaceID    string    `gorm:"column:marketplace_id;comment:地区" json:"marketplace_id"`                                // 地区
	Asin             string    `gorm:"column:asin;comment:asin" json:"asin"`                                                  // asin
	OrderedUnits     int32     `gorm:"column:ordered_units;comment:订购数量" json:"ordered_units"`                                // 订购数量
	OrderedRevenue   float64   `gorm:"column:ordered_revenue;comment:销售额" json:"ordered_revenue"`                             // 销售额
	StartTime        time.Time `gorm:"column:start_time;comment:开始时间" json:"start_time"`                                      // 开始时间
	EndTime          time.Time `gorm:"column:end_time;comment:结束时间" json:"end_time"`                                          // 结束时间
	ProfileStartTime time.Time `gorm:"column:profile_start_time;comment:站点当地时间-开始时间" json:"profile_start_time"`               // 站点当地时间-开始时间
	ProfileEndTime   time.Time `gorm:"column:profile_end_time;comment:站点当地时间-结束时间" json:"profile_end_time"`                   // 站点当地时间-结束时间
	StartHour        int32     `gorm:"column:start_hour;comment:开始时间的小时" json:"start_hour"`                                   // 开始时间的小时
	CurrencyCode     string    `gorm:"column:currency_code;comment:货币" json:"currency_code"`                                  // 货币
	EventTime        time.Time `gorm:"column:event_time;not null;comment:事件时间" json:"event_time"`                             // 事件时间
	PublishTime      time.Time `gorm:"column:publish_time;comment:推送时间" json:"publish_time"`                                  // 推送时间
	OriginMsg        string    `gorm:"column:origin_msg;comment:sqs原始消息" json:"origin_msg"`                                   // sqs原始消息
	CreateTime       time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime       time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName AmsSalesEvent's table name
func (*AmsSalesEvent) TableName() string {
	return TableNameAmsSalesEvent
}
