// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdvCampaignsSd = "t_amz_adv_campaigns_sd"

// AdvCampaignsSd mapped from table <t_amz_adv_campaigns_sd>
type AdvCampaignsSd struct {
	CampaignID  int64  `gorm:"column:campaignId;primaryKey" json:"campaignId"`
	Profileid   int64  `gorm:"column:profileid;primaryKey" json:"profileid"`
	Portfolioid int64  `gorm:"column:portfolioid" json:"portfolioid"`
	Name        string `gorm:"column:name" json:"name"`
	/*
		20情景定位
		30受众
	*/
	Tactic       string    `gorm:"column:tactic;comment:20情景定位\n30受众" json:"tactic"`
	CostType     string    `gorm:"column:costType;comment:付费类型" json:"costType"` // 付费类型
	BudgetType   string    `gorm:"column:budgetType" json:"budgetType"`
	Budget       float64   `gorm:"column:budget" json:"budget"`
	StartDate    time.Time `gorm:"column:startDate" json:"startDate"`
	EndDate      time.Time `gorm:"column:endDate" json:"endDate"`
	State        string    `gorm:"column:state" json:"state"`
	Opttime      time.Time `gorm:"column:opttime" json:"opttime"`
	CampaignType string    `gorm:"column:campaignType;default:SD" json:"campaignType"`
}

// TableName AdvCampaignsSd's table name
func (*AdvCampaignsSd) TableName() string {
	return TableNameAdvCampaignsSd
}
