// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdvCampaignsSb = "t_amz_adv_campaigns_hsa"

// AdvCampaignsSb mapped from table <t_amz_adv_campaigns_hsa>
type AdvCampaignsSb struct {
	CampaignID      int64     `gorm:"column:campaignId;primaryKey" json:"campaignId"`
	Profileid       int64     `gorm:"column:profileid;primaryKey" json:"profileid"`
	Portfolioid     int64     `gorm:"column:portfolioid" json:"portfolioid"`
	CampaignType    string    `gorm:"column:campaignType;default:SB" json:"campaignType"`
	Name            string    `gorm:"column:name" json:"name"`
	Tags            string    `gorm:"column:tags" json:"tags"`
	BudgetType      string    `gorm:"column:budgetType" json:"budgetType"`
	Budget          float64   `gorm:"column:budget" json:"budget"`
	StartDate       time.Time `gorm:"column:startDate" json:"startDate"`
	EndDate         time.Time `gorm:"column:endDate" json:"endDate"`
	State           string    `gorm:"column:state" json:"state"`
	ServingStatus   string    `gorm:"column:servingStatus" json:"servingStatus"`
	BrandEntityID   string    `gorm:"column:brandEntityId" json:"brandEntityId"`
	LandingPage     string    `gorm:"column:landingPage" json:"landingPage"`
	AdFormat        string    `gorm:"column:adFormat" json:"adFormat"`
	Creative        string    `gorm:"column:creative" json:"creative"`
	SpendingPolicy  string    `gorm:"column:spendingPolicy" json:"spendingPolicy"`
	BidOptimization string    `gorm:"column:bidOptimization" json:"bidOptimization"`
	BidMultiplier   float64   `gorm:"column:bidMultiplier" json:"bidMultiplier"`
	BidAdjustments  string    `gorm:"column:bidAdjustments" json:"bidAdjustments"`
	Opttime         time.Time `gorm:"column:opttime" json:"opttime"`
}

// TableName AdvCampaignsSb's table name
func (*AdvCampaignsSb) TableName() string {
	return TableNameAdvCampaignsSb
}
