// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOperateLog = "t_amz_adv_operate_log"

// OperateLog mapped from table <t_amz_adv_operate_log>
type OperateLog struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Profileid    int64     `gorm:"column:profileid" json:"profileid"`
	CampaignID   int64     `gorm:"column:campaignId" json:"campaignId"`
	PortfolioID  int64     `gorm:"column:portfolio_id" json:"portfolio_id"`
	AdGroupID    int64     `gorm:"column:adGroupId" json:"adGroupId"`
	Opttime      time.Time `gorm:"column:opttime" json:"opttime"`
	Operator     int64     `gorm:"column:operator" json:"operator"`
	EntityID     int64     `gorm:"column:entityId;comment:实体id" json:"entityId"` // 实体id
	Beanclasz    string    `gorm:"column:beanclasz" json:"beanclasz"`
	Beforeobject string    `gorm:"column:beforeobject" json:"beforeobject"`
	Afterobject  string    `gorm:"column:afterobject" json:"afterobject"`
	Remark       string    `gorm:"column:remark" json:"remark"`
	TargetText   string    `gorm:"column:target_text;comment:投放" json:"target_text"` // 投放
	MatchType    string    `gorm:"column:match_type;comment:匹配类型" json:"match_type"` // 匹配类型
}

// TableName OperateLog's table name
func (*OperateLog) TableName() string {
	return TableNameOperateLog
}
