// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAmzAdvAdgroupsSd = "t_amz_adv_adgroups_sd"

// AmzAdvAdgroupsSd mapped from table <t_amz_adv_adgroups_sd>
type AmzAdvAdgroupsSd struct {
	AdGroupID       int64     `gorm:"column:adGroupId;primaryKey" json:"adGroupId"`
	CampaignID      int64     `gorm:"column:campaignId;not null" json:"campaignId"`
	Profileid       int64     `gorm:"column:profileid;not null" json:"profileid"`
	BidOptimization string    `gorm:"column:bidOptimization" json:"bidOptimization"`
	Name            string    `gorm:"column:name" json:"name"`
	State           string    `gorm:"column:state" json:"state"`
	DefaultBid      float64   `gorm:"column:defaultBid" json:"defaultBid"`
	Opttime         time.Time `gorm:"column:opttime" json:"opttime"`
}

// TableName AmzAdvAdgroupsSd's table name
func (*AmzAdvAdgroupsSd) TableName() string {
	return TableNameAmzAdvAdgroupsSd
}
