// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameKeyVal = "t_kv"

// KeyVal mapped from table <t_kv>
type KeyVal struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key        string    `gorm:"column:key;not null;comment:产品SKU" json:"key"`                                          // 产品SKU
	Value      string    `gorm:"column:value;not null;comment:产品名称" json:"value"`                                       // 产品名称
	Remark     string    `gorm:"column:remark;not null;comment:产品名称" json:"remark"`                                     // 产品名称
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName KeyVal's table name
func (*KeyVal) TableName() string {
	return TableNameKeyVal
}
