// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDict = "t_sys_dict"

// SysDict mapped from table <t_sys_dict>
type SysDict struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Name        string    `gorm:"column:name;comment:类型名称" json:"name"`                         // 类型名称
	Code        string    `gorm:"column:code;comment:类型编码" json:"code"`                         // 类型编码
	Status      bool      `gorm:"column:status;comment:状态（0-正常 ,1-停用）" json:"status"`           // 状态（0-正常 ,1-停用）
	Remark      string    `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	GmtCreate   time.Time `gorm:"column:gmt_create;comment:创建时间" json:"gmt_create"`             // 创建时间
	GmtModified time.Time `gorm:"column:gmt_modified;comment:更新时间" json:"gmt_modified"`         // 更新时间
}

// TableName SysDict's table name
func (*SysDict) TableName() string {
	return TableNameSysDict
}
